#!/bin/bash

if [ $# -ne 3 ]; then
	exit 0
fi

cd $1

make testdominion > /dev/null

timeout 2 ./testdominion $3 > results.out

cd ../$2

make testdominion > /dev/null

timeout 2 ./testdominion $3 > results.out

cd ../

diff $1/results.out $2/results.out > ./comparison.out

words=`wc ./comparison.out | awk '{print $1}'`

if [ $words -ne 0 ]; then
	echo "TEST FAILED"
	exit 0
fi
echo "TEST PASSED"

