#!/bin/bash

for D in ./mutants/*;do
	cp $D/src/src.c ./testing/dominion.c
	cd testing/
	make clean
	make testdominion > /dev/null
	cd ../
	if [ ! -e ./testing/testdominion ];then
		echo $D >> DNC.txt
		continue
	fi
	timeout 5 ./testdominion 42 > OGoutput
	timeout 5 ./testing/testdominion 42 > MUTANToutput
	diff OGoutput MUTANToutput > difference
	count=`wc ./difference | awk '{print $1}'`
	if [ $count -ne 0 ]; then
		echo $D >> Killed.txt
	else
		echo $d >> Survived.txt
	fi
done
