#!/bin/bash

for D in ./mutants/*;do
	cp $D/src/src.c ./testing_facility/dominion.c
	cd testing_facility/
	make clean
	make testdominion > /dev/null
	cd ../
	if [ ! -a ./testing_facility/testdominion ];
		echo $D >> DNC.txt
		continue
	fi
	./testdominion 42 > OGoutput
	./testing_facility/testdominion 42 > MUTANToutput
	diff OGoutput MUTANToutput > difference
	count=`wc ./difference | awk '{print $1}'`
	if [ $count -ne 0 ]
		echo $D >> Killed.txt
	else
		echo $d >> Survived.txt
	fi
done
